name: 'Setup'
description: 'Checkout repo, setup Node + pnpm, and install dependencies'
inputs:
  node-version:
    description: 'Node.js version'
    default: '20'
  pnpm-version:
    description: 'pnpm version'
    default: '9'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
    - run: pnpm install
      shell: bash
